apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: coffee-ingress
  namespace: coffee-app

spec:
  ingressClassName: nginx

  rules:
    - host: coffee.local

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: frontend
                port:
                  number: 80